# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wandering by in the net
email: luca.orlandi(at)gmail.com
description: >
  # Pensieri misti vagando per la rete

  This is my primary blog site, I usually write things in many different places but this is mine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lrkwz.github.io" # the base hostname & protocol for your site
twitter_username: lrkwz
github_username:  lrkwz
linkedin_username: lrkwz
flickr_username: lrkwz
paginate: 5
permalink: pretty

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-assets
  - jekyll-sitemap

google_analytics_ua: UA-89993-1

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

theme: jekyll-theme-dinky

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
